---

- hosts: all
  become: true
  tasks:

  - name: Install Apache httpd and php package
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Enable service to start on boot
    service:
      name: httpd
      state: started

  - name: Create firewall rule for httpd service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled

  handlers:
  - name: Restart apache
    service:
      name: httpd
      state: restarted
